serenity.project.name=SWAG LABS
serenity.test.root=org.example

webdriver.driver=chrome

# Desactiva la descarga automática para evitar que WebDriverManager descargue la versión incorrecta
webdriver.autodownload=false

# Ruta absoluta al chromedriver.exe que descargaste y descomprimiste
webdriver.chrome.driver=C:/drivers/chromedriver.exe

serenity.browser.maximized=true

serenity.use.unique.browser=false
serenity.restart.browser.each.scenario=true